title: Lerntagebuch Datenformate
author: Pia
description: > # this means to ignore newlines
  WS 24/25 Kurs Schnittstellen & Datenformate

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-hacker

plugins:
- jekyll-remote-theme
